### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by SpaceWhite** [niuware/web-framework#1]
When debug mode is disabled, it just only stop showing the trace but not stop showing the exception page.
From security concern it is bad, because malicious user can know the location / directory of a script, that can be use on further vendor.

**Comment by niuware** [comment]
Thanks for your comment.
Now when the user sets the debug mode off, exception details are not displayed. This was updated on the core classes repository in commit 9c56b96. Run a 'composer update' to get these changes on your current project.
